### ISSUE TITLE
Can't fork :(

### ISSUE THREAD

**Issue by missinformed** [benbalter/situation-clock#1]
I can't seem to build:

``````
$ script/bootstrap
................................................................................
......####...######..######..##..##...####...######..######...####...##..##.....
.....##........##......##....##..##..##..##....##......##....##..##..###.##.....
......####.....##......##....##..##..######....##......##....##..##..##.###.....
.........##....##......##....##..##..##..##....##......##....##..##..##..##.....
......####...######....##.....####...##..##....##....######...####...##..##.....
................................................................................
.....................####...##.......####....####...##..##......................
....................##..##..##......##..##..##..##..##.##.......................
....................##......##......##..##..##......####........................
....................##..##..##......##..##..##..##..##.##.......................
.....................####...######...####....####...##..##......................
................................................................................
situation-clock@0.0.1 /Users/missinformed/dev/situation-clock
└── coffee-script@1.6.3

Using RedCloth 4.2.9
Using blankslate 2.1.2.4
Using fast-stemmer 1.0.2
Using colorator 0.1
Using highline 1.6.20
Using dotenv 0.9.0
Using ffi 1.9.3
Using thor 0.18.1
Using liquid 2.5.4
Using rb-fsevent 0.9.3
Using maruku 0.7.0
Using posix-spawn 0.3.8
Using yajl-ruby 1.1.0
Using redcarpet 2.3.0
Using safe_yaml 0.9.7
Using kramdown 1.2.0
Using rdiscount 2.1.7
Using bundler 1.11.2
Using parslet 1.5.0
Using classifier 1.3.3
Using commander 4.1.5
Using rb-inotify 0.9.3
Using rb-kqueue 0.2.0
Using foreman 0.63.0
Using pygments.rb 0.5.4
Using toml 0.1.0
Using listen 1.3.1
Using jekyll 1.4.2
Using github-pages 12
Bundle complete! 2 Gemfile dependencies, 29 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ script/server
................................................................................
......####...######..######..##..##...####...######..######...####...##..##.....
.....##........##......##....##..##..##..##....##......##....##..##..###.##.....
......####.....##......##....##..##..######....##......##....##..##..##.###.....
.........##....##......##....##..##..##..##....##......##....##..##..##..##.....
......####...######....##.....####...##..##....##....######...####...##..##.....
................................................................................
.....................####...##.......####....####...##..##......................
....................##..##..##......##..##..##..##..##.##.......................
....................##......##......##..##..##......####........................
....................##..##..##......##..##..##..##..##.##.......................
.....................####...######...####....####...##..##......................
................................................................................
17:13:58 web.1    | started with pid 72890
17:13:58 coffee.1 | started with pid 72891
17:13:58 coffee.1 | 5:13:58 PM - compiled assets/script.coffee
17:13:59 web.1    | /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328: warning: constant ::TimeoutError is deprecated
17:13:59 web.1    | /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/runner.rb:365:in `block in require_program': program version required (Commander::Runner::CommandError)
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/runner.rb:364:in `each'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/runner.rb:364:in `require_program'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/runner.rb:52:in `run!'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/delegates.rb:7:in `run!'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/import.rb:10:in `block in <top (required)>'
17:13:59 web.1    | /usr/local/lib/ruby/gems/2.3.0/gems/safe_yaml-0.9.7/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/safe_yaml-0.9.7/lib/safe_yaml.rb:200:in `require'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/safe_yaml-0.9.7/lib/safe_yaml.rb:200:in `<module:YAML>'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/safe_yaml-0.9.7/lib/safe_yaml.rb:132:in `<top (required)>'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-1.4.2/lib/jekyll.rb:21:in `require'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-1.4.2/lib/jekyll.rb:21:in `<top (required)>'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-1.4.2/bin/jekyll:7:in `require'
17:13:59 web.1    |     from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-1.4.2/bin/jekyll:7:in `<top (required)>'
17:13:59 web.1    |     from /usr/local/bin/jekyll:23:in `load'
17:13:59 web.1    |     from /usr/local/bin/jekyll:23:in `<main>'
17:13:59 web.1    | exited with code 1
17:13:59 system   | sending SIGTERM to all processes
17:13:59 coffee.1 | terminated by SIGTERM
$ gem update
Updating installed gems
Nothing to update
$ bundle exec jekyll build
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328: warning: constant ::TimeoutError is deprecated
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/runner.rb:365:in `block in require_program': program version required (Commander::Runner::CommandError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/runner.rb:364:in `each'
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/runner.rb:364:in `require_program'
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/runner.rb:52:in `run!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/delegates.rb:7:in `run!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.1.5/lib/commander/import.rb:10:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/safe_yaml-0.9.7/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/safe_yaml-0.9.7/lib/safe_yaml.rb:200:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/safe_yaml-0.9.7/lib/safe_yaml.rb:200:in `<module:YAML>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/safe_yaml-0.9.7/lib/safe_yaml.rb:132:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-1.4.2/lib/jekyll.rb:21:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-1.4.2/lib/jekyll.rb:21:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-1.4.2/bin/jekyll:7:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-1.4.2/bin/jekyll:7:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in `<main>'```

thoughts?
``````

**Comment by missinformed** [comment]
OK, I was able to resolve this with

```
bundle clean --force
bundle install
jekyll build
jekyll serve --no-watch
```

Thanks for pointing me towards this! Much better than timeanddate.com. ;)
